name: microclip
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=24.0
  - setuptools
  - wheel
  - libstdcxx-ng>=14
  - libgcc-ng>=14
  - ncurses
  - bzip2
  - xz
  - zlib
  - zstd
  - sqlite
  - icu
  - numpy=1.23.5
  - scipy=1.10
  - pandas=1.5
  - matplotlib=3.7
  - seaborn=0.12
  - scikit-learn=1.2.2
  - scikit-image=0.19
  - pillow=9.5
  - typing_extensions
  - sentencepiece
  - ftfy
  - einops
  - timm=0.9.12
  - pytorch=1.13.1
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - pytorch-cuda=11.7
  - ffmpeg
  - av
  - opencv
  - pkg-config
  - pycuda

  - pip:
      - scikit-learn==1.2.2
      - git+https://github.com/openai/CLIP.git@main
      - absl-py==2.1.0
      - accelerate==0.20.3
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - annotated-types==0.5.0
      - antlr4-python3-runtime==4.8
      - anyio==3.7.1
      - async-timeout==4.0.3
      - attrs==24.2.0
      - braceexpand==0.1.7
      - cachetools==5.3.3
      - charset-normalizer==3.3.2
      - cloudpickle==2.2.1
      - datasets==2.13.2
      - dill==0.3.6
      - distinctipy==1.2.3
      - distro==1.9.0
      - easyprocess==1.1
      - entrypoint2==1.1
      - exceptiongroup==1.2.2
      - filelock==3.12.2
      - fire==0.6.0
      - flake8==3.7.9
      - fonttools==4.38.0
      - frozenlist==1.3.3
      - fsspec==2023.1.0
      - future==1.0.0
      - fvcore==0.1.3.post20210317
      - gdown==4.7.3
      - google-auth==2.29.0
      - google-auth-oauthlib==0.4.6
      - grpcio==1.62.1
      - h11==0.14.0
      - httpcore==0.17.3
      - httpx==0.24.1
      - huggingface-hub==0.16.4
      - hydra-core==1.0.7
      - idna==3.6
      - imageio==2.31.2
      - importlib-metadata==6.7.0
      - importlib-resources==5.12.0
      - inquirerpy==0.3.4
      - iopath==0.1.9
      - ipykernel==6.16.2
      - ipython==8.12.2
      - jedi==0.19.2
      - joblib==1.3.2
      - jupyter-client==7.4.9
      - jupyter-core==4.12.0
      - kiwisolver==1.4.5
      - littleutils==0.2.2
      - markdown==3.4.4
      - markupsafe==2.1.5
      - matplotlib-inline==0.1.6
      - mccabe==0.6.1
      - multidict==6.0.5
      - multiprocess==0.70.14
      - nest-asyncio==1.6.0
      - networkx==2.6.3
      - nvidia-ml-py==12.535.161
      - nvitop==1.3.2
      - oauthlib==3.2.2
      - ogb==1.3.6
      - omegaconf==2.0.6
      - open-clip-torch==2.24.0
      - openai==1.39.0
      - outdated==0.2.2
      - packaging==24.0
      - parameterized==0.7.4
      - parso==0.8.4
      - pexpect==4.9.0
      - pfzy==0.3.4
      - pickleshare==0.7.5
      - portalocker==2.7.0
      - prettytable==3.7.0
      - prompt-toolkit==3.0.48
      - protobuf==3.20.3
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pyarrow==12.0.1
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycodestyle==2.5.0
      - pydantic==2.5.3
      - pydantic-core==2.14.6
      - pyflakes==2.1.1
      - pygments==2.17.2
      - pyparsing==3.1.2
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyunpack==0.3
      - pywavelets==1.3.0
      - pyyaml==6.0.1
      - pyzmq==26.2.0
      - regex==2023.12.25
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - safetensors==0.4.3
      - simplecrf==0.2.1.1
      - six==1.16.0
      - sniffio==1.3.1
      - soupsieve==2.4.1
      - submitit==1.3.3
      - tabulate==0.8.9
      - tb-nightly==2.12.0a20230113
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.6.2.2
      - termcolor==2.3.0
      - threadpoolctl==3.1.0
      - tifffile==2021.11.2
      - tokenizers==0.13.3
      - transformers==4.30.2
      - tqdm==4.66.2
      - urllib3==2.0.7
      - webdataset==0.2.100
      - werkzeug==2.2.3
      - wilds==1.2.2
      - xxhash==3.5.0
      - yacs==0.1.8
      - yapf==0.29.0
      - yarl==1.9.4
